"use client"
import { Montserrat } from 'next/font/google'
import Head from 'next/head'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-icons/font/bootstrap-icons.css'
import Sidebar from './components/sidebar'
import Navbar from './components/Navbar'
import { useEffect, useState } from 'react'
import { QueryClientProvider } from 'react-query'
import queryClient from './utils/queryClient'
import { usePathname } from 'next/navigation'
import { Toaster } from 'react-hot-toast'
const montserrat = Montserrat({ subsets: ['latin'] })


// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const path = usePathname()
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  const openSidebar = () => {
    setIsSidebarOpen(true);
  };

  const closeSidebar = () => {
    setIsSidebarOpen(false);
  };
  useEffect(() => {
    typeof document !== undefined ? require('bootstrap/dist/js/bootstrap') : null
  }, [])
  return (

    <QueryClientProvider client={queryClient}>
      <html lang="en">
        <Head>
          <meta name='viewport' content="width=device-width, initial-scale=1" />
        </Head>
        <body className={montserrat.className}>
          {path === '/' ? <>
            <Toaster position='top-center' />
            {children}
          </> : <>
            <Navbar openSidebar={openSidebar} />
            <div className="d-flex">
              <Sidebar isOpensidebar={isSidebarOpen} onClose={closeSidebar} />
              <div>
                <Toaster position='top-center' />
                {children}
              </div>
            </div>
          </>}
        </body>
      </html>
    </QueryClientProvider>

  )
}
